### ISSUE TITLE
Support more chains

### ISSUE THREAD

**Issue by realdezzy** [Normalizex/honeypot-is#1]
I stumbled on your work while trying to test tokens for honeypot scams and i just want to know if there are plans to include more chains ?

**Comment by Normalizex** [comment]
And I don't know what his plans are.
By myself, I am not the developer of the honeypot.is website and its api, I am the dev of the library that interacts with the site.

But the dev has a telegram: https://t.me/ishoneypot and channel: https://t.me/honeypotis

**Comment by realdezzy** [comment]
Thanks for the response, i will try reaching out to the developer on TG
